# This file maps filename extensions (or, really, any string ending a path,
# such as /makefile) to comemnt markers for a particular language, so that
# snippet directives can be detected in that source file

.class: //      # Java
.cs: //         # C#
.go: //         # Go
.js: //         # JavaScript
.py: "#"        # Python (must quote "#" here as it is also a YAML comment marker)
.ts: //         # TypeScript
