version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm install
      - npm test
reports:
  jest_reports:
    files:
      - report.xml
    file-format: JUNITXML
    base-directory: .