version: 0.2
phases:
  install:
    commands:
      - /sbin/sysctl -w vm.max_map_count=2251954
      - /sbin/sysctl -w fs.file-max=65536
  pre_build:
    commands:
      - ulimit -a
      - codebuild-breakpoint
      - |
        for file in $(git diff --name-only HEAD HEAD~1); do
          echo -n "$file => "
          case $file in
          csharp/*)
            echo "csharp changes"
            echo "csharp" >> changed
            ;;
          go/*)
            echo "go changes"
            echo "go" >> changed
            ;;
          java/*)
            echo "java changes"
            echo "java" >> changed
            ;;
          nodejs/*)
            echo "nodejs changes"
            echo "nodejs" >> changed
            ;;
          python/*)
            echo "python changes"
            echo "python" >> changed
            ;;
          *)
            echo "unmatched changes"
            ;;
          esac
        done
  build:
    commands:
      - |
        if [ -f changed ]; then
          echo "changed file exists"
          cat changed
        else
          echo "changed file does not exist, so no changes"
          exit 0
        fi
        HAS_CSHARP=$(grep csharp changed)
        HAS_GO=$(grep go changed)
        HAS_JAVA=$(grep java changed)
        HAS_NODEJS=$(grep nodejs changed)
        HAS_PYTHON=$(grep python changed)

        if [ -n "$HAS_CSHARP" ]; then
          docker run --rm --net=host -t -v $PWD:$PWD -w $PWD jsii/superchain:1-buster-slim-node18 /bin/bash -c "scripts/build-csharp.sh"
          [[ $? -eq 0 ]] || exit $?
        fi

        if [ -n "$HAS_GO" ]; then
          docker run --rm --net=host -t -v $PWD:$PWD -w $PWD jsii/superchain:1-buster-slim-node18 /bin/bash -c "scripts/build-go.sh"
          [[ $? -eq 0 ]] || exit $?
        fi

        if [ -n "$HAS_JAVA" ]; then
          docker run --rm --net=host -t -v $PWD:$PWD -w $PWD jsii/superchain:1-buster-slim-node18 /bin/bash -c "scripts/build-java.sh"
          [[ $? -eq 0 ]] || exit $?
        fi

        if [ -n "$HAS_NODEJS" ]; then
          docker run --rm --net=host -t -v $PWD:$PWD -w $PWD jsii/superchain:1-buster-slim-node18 /bin/bash -c "scripts/build-typescript.sh"
          [[ $? -eq 0 ]] || exit $?
        fi

        if [ -n "$HAS_PYTHON" ]; then
          docker run --rm --net=host -t -v $PWD:$PWD -w $PWD jsii/superchain:1-buster-slim-node18 /bin/bash -c "scripts/build-python.sh"
          [[ $? -eq 0 ]] || exit $?
        fi

        exit 0
