version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo update npm...
      - npm update -g npm
      - node -v
      - npm -v
      - echo npm environment run
      - npm install -g create-react-app
  build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - npm install
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build