# See https://doc.mergify.io

pull_request_rules:
  - name: build
    actions:
      post_check:
        title: |
          {% if check_succeed %}
          Your pull request was successfully built
          {% else %}
          Your pull request has caused a build to fail
          {% endif %}
    conditions:
      - or:
        - -files~=^typescript/ # if typescript files did not change, continue
        - status-success=build-typescript # if typescript files have changed, wait for build
      - or:
        - -files~=^java/ # if java files did not change, continue
        - status-success=build-java # if java files have changed, wait for build
      - or:
        - -files~=^python/ # if python files did not change, continue
        - status-success=build-python # if python files have changed, wait for build
      - or:
        - -files~=^csharp/ # if csharp files did not change, continue
        - status-success=build-csharp  # if csharp files have changed, wait for build

  - name: automatic merge
    actions:
      comment:
        message: Thank you for contributing! Your pull request is now being automatically merged.
      merge:
        strict: smart
        method: squash
        strict_method: merge
      delete_head_branch: {}
      dismiss_reviews: {}
    conditions:
      - -title~=(WIP|wip)
      - -label~=^(blocked|do-not-merge)
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      - "#changes-requested-reviews-by=0"
      - status-success=Semantic Pull Request
      - status-success=build

  - name: remove stale reviews
    actions:
      dismiss_reviews: {}
    conditions:
      - base=master
  - name: if fails conventional commits
    actions:
      comment:
        message: Title does not follow the guidelines of [Conventional Commits](https://www.conventionalcommits.org). Please adjust title before merge.
    conditions:
      - -status-success=Semantic Pull Request
