name: 'Setup Language'
description: 'Set up the environment for the specified language'
inputs:
  language:
    description: 'The programming language to set up'
    required: true
runs:
  using: 'composite'
  steps:
  - name: Set up Go
    uses: actions/setup-go@v5
    if: ${{ matrix.language == 'go' }}
    with:
      go-version: '1.20'
  - uses: actions/setup-node@v4
    if: ${{matrix.language == 'typescript'}}
    with:
      node-version: 18
  - uses: actions/setup-java@v4
    if: ${{matrix.language == 'java'}}
    with:
      distribution: 'corretto'
      java-version: '17'
  - uses: actions/setup-python@v5
    if: ${{matrix.language == 'python'}}
    with:
      python-version: '3.10'
  - uses: actions/setup-dotnet@v4
    if: ${{matrix.language == 'csharp'}}
    with:
      dotnet-version: 8