<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>apigateway_cognito_lambda_dynamodb</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
      <!-- CDK Construct Library dependencies -->
      <PackageReference Include="Amazon.CDK.Lib" Version="[2.262.0,3.0.0)" />
      <PackageReference Include="Constructs" Version="10.*" />
    </ItemGroup>
</Project>
