import { CfnDataSet } from "aws-cdk-lib/aws-quicksight";
/**
 * @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-dataset-inputcolumn.html
 */
export const inputColumns: CfnDataSet.InputColumnProperty[] = [
  { "name": "Country Name", "type": "STRING"},
  { "name": "Country Code", "type": "STRING"},
  { "name": "1960", "type": "STRING"},
  { "name": "1961", "type": "STRING"},
  { "name": "1962", "type": "STRING"},
  { "name": "1963", "type": "STRING"},
  { "name": "1964", "type": "STRING"},
  { "name": "1965", "type": "STRING"},
  { "name": "1966", "type": "STRING"},
  { "name": "1967", "type": "STRING"},
  { "name": "1968", "type": "STRING"},
  { "name": "1969", "type": "STRING"},
  { "name": "1970", "type": "STRING"},
  { "name": "1971", "type": "STRING"},
  { "name": "1972", "type": "STRING"},
  { "name": "1973", "type": "STRING"},
  { "name": "1974", "type": "STRING"},
  { "name": "1975", "type": "STRING"},
  { "name": "1976", "type": "STRING"},
  { "name": "1977", "type": "STRING"},
  { "name": "1978", "type": "STRING"},
  { "name": "1979", "type": "STRING"},
  { "name": "1980", "type": "STRING"},
  { "name": "1981", "type": "STRING"},
  { "name": "1982", "type": "STRING"},
  { "name": "1983", "type": "STRING"},
  { "name": "1984", "type": "STRING"},
  { "name": "1985", "type": "STRING"},
  { "name": "1986", "type": "STRING"},
  { "name": "1987", "type": "STRING"},
  { "name": "1988", "type": "STRING"},
  { "name": "1989", "type": "STRING"},
  { "name": "1990", "type": "STRING"},
  { "name": "1991", "type": "STRING"},
  { "name": "1992", "type": "STRING"},
  { "name": "1993", "type": "STRING"},
  { "name": "1994", "type": "STRING"},
  { "name": "1995", "type": "STRING"},
  { "name": "1996", "type": "STRING"},
  { "name": "1997", "type": "STRING"},
  { "name": "1998", "type": "STRING"},
  { "name": "1999", "type": "STRING"},
  { "name": "2000", "type": "STRING"},
  { "name": "2001", "type": "STRING"},
  { "name": "2002", "type": "STRING"},
  { "name": "2003", "type": "STRING"},
  { "name": "2004", "type": "STRING"},
  { "name": "2005", "type": "STRING"},
  { "name": "2006", "type": "STRING"},
  { "name": "2007", "type": "STRING"},
  { "name": "2008", "type": "STRING"},
  { "name": "2009", "type": "STRING"},
  { "name": "2010", "type": "STRING"},
  { "name": "2011", "type": "STRING"},
  { "name": "2012", "type": "STRING"},
  { "name": "2013", "type": "STRING"},
  { "name": "2014", "type": "STRING"},
  { "name": "2015", "type": "STRING"},
  { "name": "2016", "type": "STRING"},
  { "name": "2017", "type": "STRING"},
  { "name": "2018", "type": "STRING"},
  { "name": "2019", "type": "STRING"},
  { "name": "2020", "type": "STRING"},
  { "name": "2021", "type": "STRING"},
  { "name": "2022", "type": "STRING"},
  { "name": "2023", "type": "STRING"}
]
