AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-test-package

  Sample SAM Template for lambda-test-package

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Tags:
      Project: Demo Cross Region Code Artifact
  Api:
    TracingEnabled: True

Resources:
  TestPackageLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      ContentUri: layers
      CompatibleRuntimes:
        - python3.9
        - python3.8
      RetentionPolicy: Delete

  TestPackageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/test-package
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
        - !Ref TestPackageLayer

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TestPackageFunction:
    Description: "TestPackageFunction Lambda Function ARN"
    Value: !GetAtt TestPackageFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for TestPackageFunction"
    Value: !GetAtt TestPackageFunctionRole.Arn
