name: Build Java PR

on:
  pull_request:
    paths:
      - java/**

jobs:
  build-java:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Runs docker build with JSII superchain
      run: docker run --rm --net=host -t -v $PWD:$PWD -w $PWD jsii/superchain /bin/bash -c "scripts/build-java.sh"
