# Automated actions for PRs against the v2-main branch
name: Core Contributor Label
on:
  pull_request:
    types:
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  core-label:
    env:
      CORE_MEMBERS: eladb,RomainMuller,garnaat,nija-at,skinny85,rix0rrr,NGL321,Jerry-AWS,MrArnoldPalmer,NetaNir,iliapolo,njlynch,ericzbeard,ccfife,fulghum,pkandasamy91,SoManyHs,uttarasridhar
    if: contains(env.CORE_MEMBERS.split(','), github.event.pull_request.user.login)
    runs-on: ubuntu-latest
    steps:
    - uses: andymckay/labeler@1.0.2
      with:
        add-labels: "core-contributor"
        ignore-if-labeled: true
        github-token: "${{ secrets.GITHUB_TOKEN }}"
